// flow-typed signature: 0a8d09ae93efa06538dd3a340b718c97
// flow-typed version: <<STUB>>/babel-webpack-plugin_v0.1.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-webpack-plugin/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-webpack-plugin/index' {
  declare module.exports: $Exports<'babel-webpack-plugin'>;
}
declare module 'babel-webpack-plugin/index.js' {
  declare module.exports: $Exports<'babel-webpack-plugin'>;
}
declare module 'babel-webpack-plugin/test/test.js' {
  declare module.exports: $Exports<'babel-webpack-plugin/test/test'>;
}
