// flow-typed signature: 76d79940b36ca0e2d9d7bba793143c59
// flow-typed version: <<STUB>>/css-modules-flow-types-printer_v0.3.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-modules-flow-types-printer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-modules-flow-types-printer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-modules-flow-types-printer/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-modules-flow-types-printer/dist/index.js' {
  declare module.exports: $Exports<'css-modules-flow-types-printer/dist/index'>;
}
