// flow-typed signature: f487aeb48ae23227ab01f7b279ac3d3b
// flow-typed version: <<STUB>>/csso-loader_v0.3.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csso-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csso-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'csso-loader/index' {
  declare module.exports: $Exports<'csso-loader'>;
}
declare module 'csso-loader/index.js' {
  declare module.exports: $Exports<'csso-loader'>;
}
