// flow-typed signature: ef381cb020a4bd7625e87dbff92aeac8
// flow-typed version: <<STUB>>/gulp-stylint_v4.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-stylint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-stylint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-stylint/index' {
  declare module.exports: $Exports<'gulp-stylint'>;
}
declare module 'gulp-stylint/index.js' {
  declare module.exports: $Exports<'gulp-stylint'>;
}
